# X04v1.3
# ESP32-S3 N8
# Deep Sleep
# Soil Sensor RS485

substitutions:
  dev: T44
  name: t44x04soil

deep_sleep:
  id: sleep1
  run_duration: 50s
  sleep_duration: 10min

esphome:
  name: ${name}

esp32:
  #board: adafruit_feather_esp32s3 # N4 R2
  board: esp32-s3-devkitc-1 # N8
  #board: esp32-c6-devkitc-1
  framework:
    type: arduino
  flash_size: 8MB
  variant: esp32s3

wifi:
  output_power: 15db
  
  ssid: !secret wifi_ssid
  password: !secret wifi_key
  
  ap:
    ssid: "Easy-HAN-${dev}"
    password: edpbox123
    ap_timeout: 15s # change me

captive_portal:

###

esp32_ble_tracker:
bluetooth_proxy:

###

web_server:
  local: true
  
logger:
  level: debug

api:
  reboot_timeout: 30min

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: esptime

button:
  - platform: restart
    name: "${dev} ESP Restart"

  - platform: template
    name: "${dev} ESP Prevent Sleep"
    on_press:
      then:
        - deep_sleep.prevent: sleep1

switch:
  - platform: gpio
    id: led_pin
    pin:
      number: 39
      inverted: yes

one_wire:
  - platform: gpio
    pin: 38

####

uart:

#ifdef ESP32S3
#define HAN_DIR 16
#define HAN_TX 15
#define HAN_RX 17

#elif ESP32C6
#define HAN_DIR 3
#define HAN_TX 5
#define HAN_RX 4

  id: modbus_serial
  rx_pin: 17
  tx_pin: 15
  baud_rate: 4800
  stop_bits: 1

modbus:
  flow_control_pin: 16
  id: modbus1
  uart_id: modbus_serial
  send_wait_time: 500ms

modbus_controller:
  - id: edpbox
    update_interval: 5s
    address: 0x1
    command_throttle: 500ms
    setup_priority: -10

####

sensor:

####

  - platform: dallas_temp
    name: "${dev} DS18B20 Temperature"
    device_class: temperature
    state_class: measurement
    update_interval: 5s

####

  - platform: modbus_controller
    name: "${dev} Soil Humidity"
    address: 0
    unit_of_measurement: "%"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: humidity
    state_class: measurement

  - platform: modbus_controller
    name: "${dev} Soil Temperature"
    address: 1
    unit_of_measurement: "°C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
    state_class: measurement

####

  - platform: adc
    name: "${dev} Adc In raw"
    id: adc_in
    raw: true
    pin: 1
    attenuation: 0dB
    samples: 20
    accuracy_decimals: 0
    device_class: ""
    unit_of_measurement: "raw"
    state_class: measurement
    update_interval: 5s

  - platform: template
    name: "${dev} Adc In"
    lambda: |-
      return  id(adc_in).state / 257.2580645161;
    accuracy_decimals: 2
    device_class: voltage
    unit_of_measurement: "V"
    state_class: measurement
    update_interval: 5s

###

  - platform: adc
    name: "${dev} Adc A2 raw"
    id: adc_a2
    raw: true
    pin: 2
    attenuation: 0dB
    samples: 20
    accuracy_decimals: 0
    device_class: ""
    unit_of_measurement: "raw"
    state_class: measurement
    update_interval: 5s


# 4-20ma Water Level // Resistor 47 Ohm = <1V
# Tasmota: ESP8266 raw: 323   // 6*1V: 1.89V  // meters: 0.38m
# ESPHome S3       raw: 1265 

# Tasmota # ESPHome # Div y/x
# 323     # 1265    # 3.916408
# 360     # 1360    # 3.777777
# 387     # 1621    # 4.188630
# 498     # 1920    # 3.855421
# 536     # 2182    # 4.070895
# 646     # 2570    # 3.978328

  - platform: template
    name: "${dev} Adc A2"
    lambda: |-
      return  id(adc_a2).state * 3.9; // to fix
    accuracy_decimals: 2
    device_class: voltage
    unit_of_measurement: "V"
    state_class: measurement
    update_interval: 5s

###

  - platform: template
    name: "${dev} ESP Free Heap"
    lambda: |-
      float heap = ESP.getFreeHeap();
      // float heap = esp_get_free_heap_size();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    icon: mdi:chip
    state_class: measurement
    update_interval: 5s

  - platform: wifi_signal
    name: "${dev} ESP Signal"
    unit_of_measurement: "dB"
    state_class: measurement
    update_interval: 5s

  - platform: uptime
    name: "${dev} ESP Uptime"
    filters:
      - lambda: return x;
    unit_of_measurement: "s"
    accuracy_decimals: 0
    device_class: ""
    update_interval: 5s

### ### ###

### ### ###


###


#######
# eof #
#######
